create sequence hibernate_sequence start with 1 increment by  1;
create table customers (customer_id number(10,0) not null, address varchar2(255 char), contact_no varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), primary key (customer_id));
create table employees (employee_id number(10,0) not null, available_status number(1,0) not null, emp_address varchar2(255 char), emp_contact_no varchar2(255 char), emp_role number(10,0), first_name varchar2(255 char), last_name varchar2(255 char), team_id number(10,0), primary key (employee_id));
create table orderedservices (ordered_service_id number(10,0) not null, delivery_date timestamp, installation_address varchar2(255 char), progress number(10,0) not null, service_denial_reason varchar2(255 char), service_status number(10,0), start_date timestamp, employee_id number(10,0), project_id number(10,0), service_id number(10,0), primary key (ordered_service_id));
create table orderedtaskteam (ordered_task_id number(10,0) not null, team_id number(10,0), primary key (ordered_task_id));
create table ordertasks (ordered_task_id number(10,0) not null, approved number(1,0), end_date timestamp, start_date timestamp, task_denial_reason varchar2(255 char), task_status number(10,0), employee_id number(10,0), ordered_service_id number(10,0), task_id number(10,0), primary key (ordered_task_id));
create table projects (project_id number(10,0) not null, delivery_date timestamp, name varchar2(255 char), progress number(10,0) not null, start_date timestamp, status number(10,0), customer_id number(10,0), employee_id number(10,0), primary key (project_id));
create table services (service_id number(10,0) not null, description varchar2(255 char), name varchar2(255 char), primary key (service_id));
create table serviceworkflow (work_flow_id number(10,0) not null, dependent_on number(10,0) not null, seq_number number(10,0) not null, service_id number(10,0), task_id number(10,0), team_id number(10,0), primary key (work_flow_id));
create table tasks (task_id number(10,0) not null, approval_needed number(1,0), description varchar2(255 char), end_date timestamp, name varchar2(255 char), start_date timestamp, primary key (task_id));
create table teams (team_id number(10,0) not null, description varchar2(255 char), name varchar2(255 char), employee_id number(10,0), primary key (team_id));
create table users (user_id number(10,0) not null, active number(1,0), username varchar2(255 char), password varchar2(255 char), employee_id number(10,0), primary key (user_id));
alter table employees add constraint FKa5cxjw6yuqlbp0np1g51o03gf foreign key (team_id) references teams;
alter table orderedservices add constraint foreign key (employee_id) references employees;
alter table orderedservices add constraint foreign key (project_id) references projects;
alter table orderedservices add constraint foreign key (service_id) references services;
alter table orderedtaskteam add constraint foreign key (team_id) references teams;
alter table ordertasks add constraint foreign key (employee_id) references employees;
alter table ordertasks add constraint foreign key (ordered_service_id) references orderedservices;
alter table ordertasks add constraint foreign key (task_id) references tasks;
alter table projects add constraint foreign key (customer_id) references customers;
alter table projects add constraint foreign key (employee_id) references employees;
alter table serviceworkflow add constraint foreign key (service_id) references services;
alter table serviceworkflow add constraint foreign key (task_id) references tasks;
alter table serviceworkflow add constraint foreign key (team_id) references teams;
alter table teams add constraint foreign key (employee_id) references employees;
alter table users add constraint foreign key (employee_id) references employees;